name: Conditions

on:
  workflow_dispatch:

jobs:
  build:
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting
        if: ${{ true }}
        run: |
          echo $CONTAINS
          echo $FORMAT
          printf "$TO_JSON"
          echo github.triggering_actor
        env:
          CONTAINS: ${{ contains('GitHub Actions', 'actions') }}
          FORMAT: ${{ format('This {0} {1}', 'is', 'cool') }}
          TO_JSON: ${{ toJSON(github.event) }}
  deploy:
    if: ${{ github.triggering_actor == 'tamtanns' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run if previou job succeeds
        run: |
          echo "Everything is working as expected"
