name: Filtered Runs with paths-ignore

run-name: Run of the Filtered Runs with paths-ignore workflow

on:
  # Workflow run trigger events
  push:
    branches:
    - main
    - 'release/**'
    - '!test/**'
    paths-ignore:
    - "**.md"
    - "**/**.md"

jobs:
  # First job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # By default, the runner will use Bash on Linux/MacOS runners
      # Bash is supported on all runners
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a null-line script
        run: |
          echo add other actions to build,
          echo test, and deploy our projet.
