name: Functions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting
        run: |
          echo $CONTAINS
          echo $FORMAT
          printf $TO_JSON
        env:
          CONTAINS: ${{ contains('GitHub Actions', 'actions') }}
          FORMAT: ${{ format('This {0} {1}', 'is', 'cool') }}
          EVENT: ${{ toJSON(github.event) }}
