name: Matrices

on:
  workflow-dispatch:

jobs:
  matrix_tests:
    strategy:
      matrix:
        version: ["0.1.0", "0.1.1", "0.2.0"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: run a multi-line script
        run: |
          echo "Running on: ${{ matrix.os }} version: ${{ martix.version }}"
