name: "Lesson 3 - Exercise 1 - Reusable"

on:
    workflow_call:
      inputs:
          actor:
              description: "The person who will receive the greeting"
              required: true
              type: strin

jobs:
    greeting:
      runs-on: ubuntu-latest
      steps:
        - name: Greetings message
          run: |
            echo "Well done: $ACTOR you've implemented reusable workflows successfully!"
          env:
            ACTOR: ${{ inputs.actor }}
