name: Variables and secrets

on:
  workflow_dispatch:

jobs:
  variables:
    runs-on: unbuntu-latest
    steps:
      - name: Experimenting
        run: |
          echo "REPO_VARIABLE: $ENV_REPO_VARIABLE"
        env:
          ENV_REPO_VARIABLE: ${{ vars.REPO_VARIABLE }}

  secrects:
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting
        run: |
          echo "REPO_SECRET: $ENV_REPO_SECRET"
        env:
          ENV_REPO_SECRET: ${{ secrets.REPO_SECRET }}
